In [1]:
import pandas as pd

In [2]:
url = "https://github.com/Reemaalsharif/Saudi-Data-Internship-Readiness-Map/raw/refs/heads/main/data/saudi_data_jobs_dataset.csv"

df = pd.read_csv(url)
df.head()

,job_id,job_title,company,city,role_type,experience_level,skills,tools,source,job_link,date_collected,notes
0,1,Data Analyst,ALESAYI HOLDING,Jeddah,Data Analyst,Entry level / 3 years,"customer data analysis, operational performanc...","Excel, PowerPoint, dashboards",LinkedIn,https://sa.linkedin.com/jobs/view/data-analyst...,2026-06-30,Customer experience data analyst role in autom...
1,2,Geological Data Scientist,Maaden Barrick Copper Company,Mahd Adh Dhahab,Data Scientist,Entry level / 2-5 years,"geological data management, data quality manag...","SQL, Python, Power BI, Tableau, relational dat...",LinkedIn,https://sa.linkedin.com/jobs/view/geological-d...,2026-06-30,Mining sector data science role. Focuses on ge...
2,3,Data Analyst,PrimeGate for Communications and IT,Riyadh,Data Analyst,Entry level,"data analysis, insights generation, dashboardi...","SQL, Power BI, Tableau, Looker, Excel, Python,...",LinkedIn,https://sa.linkedin.com/jobs/view/data-analyst...,2026-06-30,Entry-level data analyst role for Madinaty Sup...
3,4,Analyst Pricing Analytics and Insights,Schneider Electric,Saudi Arabia,Business / Pricing Analytics,Entry level,"pricing analytics, data analysis, data interpr...","data visualization, dashboards, charts, reports",LinkedIn,https://sa.linkedin.com/jobs/view/analyst-pric...,2026-06-30,Entry-level pricing analytics role. Focuses on...
4,5,Power BI Developer,Acuative Middle East,Jeddah,BI / Power BI Developer,Mid-level,"Power BI dashboard development, business intel...","Power BI Desktop, Power BI Service, DAX, Power...",LinkedIn,https://sa.linkedin.com/jobs/view/power-bi-dev...,2026-06-30,Mid-level Power BI Developer role in Jeddah. F...

In [3]:
df.columns

Index(['job_id', 'job_title', 'company', 'city', 'role_type',
       'experience_level', 'skills', 'tools', 'source', 'job_link',
       'date_collected', 'notes'],
      dtype='object')

In [6]:
df['city'].value_counts()

city
Riyadh             17
Saudi Arabia        4
Jeddah              3
Mahd Adh Dhahab     1
Name: count, dtype: int64

In [7]:
df['city_cleaned'] = df['city'].replace({
    'Saudi Arabia': 'Not specified'
})

df['city_cleaned'].value_counts()

city_cleaned
Riyadh             17
Not specified       4
Jeddah              3
Mahd Adh Dhahab     1
Name: count, dtype: int64

In [12]:
def categorize_experience(exp):
    exp = str(exp).lower()

    if 'intern' in exp or 'trainee' in exp:
        return 'Internship'
    elif 'entry' in exp or 'junior' in exp or 'fresh' in exp or 'assistant' in exp or 'analyst program' in exp:
        return 'Entry Level'
    elif 'mid' in exp or '2' in exp or '3' in exp or '4' in exp:
        return 'Mid-Level'
    elif 'senior' in exp or 'lead' in exp or 'manager' in exp or '5' in exp:
        return 'Senior'
    else:
        return 'Not Specified'

df['experience_category'] = df['experience_level'].apply(categorize_experience)

df['experience_category'].value_counts()

experience_category
Entry Level      12
Mid-Level        10
Internship        2
Not Specified     1
Name: count, dtype: int64

In [13]:
def categorize_role(title):
    title = str(title).lower()

    if 'intern' in title or 'trainee' in title:
        return 'Internship'
    elif 'business intelligence' in title or 'bi' in title or 'power bi' in title:
        return 'BI'
    elif 'data scientist' in title or 'machine learning' in title:
        return 'Data Science'
    elif 'data analyst' in title or 'analysis' in title or 'analytics' in title:
        return 'Data Analysis'
    elif 'ai' in title or 'artificial intelligence' in title:
        return 'AI'
    elif 'governance' in title or 'data management' in title:
        return 'Governance'
    else:
        return 'Other'

df['role_category'] = df['job_title'].apply(categorize_role)

df['role_category'].value_counts()

role_category
Data Analysis    9
Other            5
AI               4
BI               3
Data Science     2
Governance       2
Name: count, dtype: int64

In [14]:
df[['job_title', 'city', 'city_cleaned', 'experience_level', 'experience_category', 'role_category']].head(10)

,job_title,city,city_cleaned,experience_level,experience_category,role_category
0,Data Analyst,Jeddah,Jeddah,Entry level / 3 years,Entry Level,Data Analysis
1,Geological Data Scientist,Mahd Adh Dhahab,Mahd Adh Dhahab,Entry level / 2-5 years,Entry Level,Data Science
2,Data Analyst,Riyadh,Riyadh,Entry level,Entry Level,Data Analysis
3,Analyst Pricing Analytics and Insights,Saudi Arabia,Not specified,Entry level,Entry Level,Data Analysis
4,Power BI Developer,Jeddah,Jeddah,Mid-level,Mid-Level,BI
5,2026 KSA Analyst Program - Data and AI Analyst,Riyadh,Riyadh,Assistant level / Analyst Program,Entry Level,AI
6,Data Scientist I,Saudi Arabia,Not specified,Entry level / 0-2 years,Entry Level,Data Science
7,Specialist Operations Performance,Jeddah,Jeddah,Assistant level / 2+ years,Entry Level,Other
8,Data Analyst Fraud Protection,Riyadh,Riyadh,Mid-level,Mid-Level,Data Analysis
9,Junior Digital Marketing Analyst,Riyadh,Riyadh,Entry level / 0-2 years,Entry Level,Other

In [11]:
df.to_csv('saudi_data_jobs_cleaned.csv', index=False)

In [15]:
df['city_cleaned'].value_counts()

city_cleaned
Riyadh             17
Not specified       4
Jeddah              3
Mahd Adh Dhahab     1
Name: count, dtype: int64

In [16]:
df['experience_category'].value_counts()

experience_category
Entry Level      12
Mid-Level        10
Internship        2
Not Specified     1
Name: count, dtype: int64

In [17]:
 df['experience_category'].value_counts()

experience_category
Entry Level      12
Mid-Level        10
Internship        2
Not Specified     1
Name: count, dtype: int64

In [18]:
df.to_csv('saudi_data_jobs_cleaned.csv', index=False)

In [19]:
df[df['experience_category'] == 'Not Specified'][['job_title', 'experience_level']]

                     job_title experience_level
13  Data Management Specialist        Associate

In [20]:
def categorize_experience(exp):
    exp = str(exp).lower()

    if 'intern' in exp or 'trainee' in exp:
        return 'Internship'
    elif 'entry' in exp or 'junior' in exp or 'fresh' in exp or 'assistant' in exp or 'analyst program' in exp:
        return 'Entry Level'
    elif 'mid' in exp or 'associate' in exp or '2' in exp or '3' in exp or '4' in exp:
        return 'Mid-Level'
    elif 'senior' in exp or 'lead' in exp or 'manager' in exp or '5' in exp:
        return 'Senior'
    else:
        return 'Not Specified'

df['experience_category'] = df['experience_level'].apply(categorize_experience)

df['experience_category'].value_counts()

experience_category
Entry Level    12
Mid-Level      11
Internship      2
Name: count, dtype: int64

In [21]:
df.to_csv('saudi_data_jobs_cleaned.csv', index=False)