# Data Cleaning

## Objective

Clean and transform the Saudi data jobs dataset to prepare it for analysis and visualization.

## Dataset Overview

This notebook uses the original Saudi data jobs dataset and applies cleaning and transformation steps to create a dataset ready for further analysis.

## Cleaning Steps

This notebook handles:

- City standardization.
- Experience categorization.
- Role categorization.
- Creating analysis-ready columns.
- Exporting the cleaned dataset.

In [1]:
import pandas as pd

url = "https://github.com/Reemaalsharif/Saudi-Data-Internship-Readiness-Map/raw/refs/heads/main/data/saudi_data_jobs_dataset.csv"

df = pd.read_csv(url)

df.columns

Index(['job_id', 'job_title', 'company', 'city', 'role_type',
       'experience_level', 'skills', 'tools', 'source', 'job_link',
       'date_collected', 'notes'],
      dtype='object')

In [ ]:
df.columns

Index(['job_id', 'job_title', 'company', 'city', 'role_type',
       'experience_level', 'skills', 'tools', 'source', 'job_link',
       'date_collected', 'notes'],
      dtype='object')

## City Data Cleaning

Standardizing city values to improve consistency during analysis.

In [ ]:
df['city'].value_counts()

city
Riyadh                         28
Jeddah                         10
Saudi Arabia                    5
Mahd Adh Dhahab                 1
King Abdullah Economic City     1
Name: count, dtype: int64

In [ ]:
df['city_cleaned'] = df['city'].replace({
    'Saudi Arabia': 'Not specified'
})

df['city_cleaned'].value_counts()

city_cleaned
Riyadh                         28
Jeddah                         10
Not specified                   5
Mahd Adh Dhahab                 1
King Abdullah Economic City     1
Name: count, dtype: int64

## Experience Category Creation

Creating simplified experience categories to make experience requirements easier to analyze and visualize.

In [ ]:
def categorize_experience(exp):
    exp = str(exp).lower()

    if 'intern' in exp or 'trainee' in exp:
        return 'Internship'

    elif 'entry' in exp or 'junior' in exp or 'fresh' in exp or 'assistant' in exp or 'analyst program' in exp:
        return 'Entry Level'

    elif 'mid' in exp or 'associate' in exp or '2' in exp or '3' in exp or '4' in exp:
        return 'Mid-Level'

    elif 'senior' in exp or 'lead' in exp or 'manager' in exp or '5' in exp:
        return 'Senior'

    else:
        return 'Not Specified'

In [ ]:
df['experience_category'] = df['experience_level'].apply(categorize_experience)

df['experience_category'].value_counts()

experience_category
Mid-Level        22
Entry Level      12
Not Specified     7
Internship        3
Senior            1
Name: count, dtype: int64

## Role Category Creation

Grouping job titles into broader categories to support career path analysis.

In [ ]:
def categorize_role(title):
    title = str(title).lower()

    if 'intern' in title or 'trainee' in title:
        return 'Internship'

    elif 'business intelligence' in title or 'bi' in title or 'power bi' in title:
        return 'BI'

    elif 'data scientist' in title or 'machine learning' in title:
        return 'Data Science'

    elif 'data analyst' in title or 'analysis' in title or 'analytics' in title:
        return 'Data Analysis'

    elif 'ai' in title or 'artificial intelligence' in title:
        return 'AI'

    elif 'governance' in title or 'data management' in title:
        return 'Governance'

    else:
        return 'Other'

In [ ]:
df['role_category'] = df['job_title'].apply(categorize_role)

df['role_category'].value_counts()

role_category
Other            12
Data Analysis    11
BI                7
AI                6
Data Science      5
Governance        3
Internship        1
Name: count, dtype: int64

## Clean Dataset Review

Reviewing the newly created columns after data transformation.

In [ ]:
df[['job_title',
    'city',
    'city_cleaned',
    'experience_level',
    'experience_category',
    'role_category']].head(10)

,job_title,city,city_cleaned,experience_level,experience_category,role_category
0,Data Analyst,Jeddah,Jeddah,Entry level / 3 years,Entry Level,Data Analysis
1,Geological Data Scientist,Mahd Adh Dhahab,Mahd Adh Dhahab,Entry level / 2-5 years,Entry Level,Data Science
2,Data Analyst,Riyadh,Riyadh,Entry level,Entry Level,Data Analysis
3,Analyst Pricing Analytics and Insights,Saudi Arabia,Not specified,Entry level,Entry Level,Data Analysis
4,Power BI Developer,Jeddah,Jeddah,Mid-level,Mid-Level,BI
5,2026 KSA Analyst Program - Data and AI Analyst,Riyadh,Riyadh,Assistant level / Analyst Program,Entry Level,AI
6,Data Scientist I,Saudi Arabia,Not specified,Entry level / 0-2 years,Entry Level,Data Science
7,Specialist Operations Performance,Jeddah,Jeddah,Assistant level / 2+ years,Entry Level,Other
8,Data Analyst Fraud Protection,Riyadh,Riyadh,Mid-level,Mid-Level,Data Analysis
9,Junior Digital Marketing Analyst,Riyadh,Riyadh,Entry level / 0-2 years,Entry Level,Other

## Final Data Validation

Checking the final cleaned categories before exporting the dataset.

In [ ]:
df['city_cleaned'].value_counts()

city_cleaned
Riyadh                         28
Jeddah                         10
Not specified                   5
Mahd Adh Dhahab                 1
King Abdullah Economic City     1
Name: count, dtype: int64

In [ ]:
df['experience_category'].value_counts()

experience_category
Mid-Level        22
Entry Level      12
Not Specified     7
Internship        3
Senior            1
Name: count, dtype: int64

In [ ]:
df['role_category'].value_counts()

role_category
Other            12
Data Analysis    11
BI                7
AI                6
Data Science      5
Governance        3
Internship        1
Name: count, dtype: int64

## Export Clean Dataset

Saving the final cleaned dataset for analysis and Power BI development.

In [ ]:
df.to_csv('saudi_data_jobs_cleaned.csv', index=False)

## Review Unclassified Experience Levels

Reviewing records where experience level could not be categorized to understand remaining unclear cases.

In [ ]:
df[df['experience_category'] == 'Not Specified'][['job_title', 'experience_level']]

,job_title,experience_level
26,"ICQA Researcher, MEATR ICQA",1+ years data analytics or automation experience
27,Data Analyst Excel - Remote,Proven experience / Not specified years
28,Data Scientist Expert (AI Community),Basic proficiency / Qualification exam
30,AI Trainer - Freelance Data Annotator,1+ years professional experience
32,Performance Analyst,Not specified
34,Data Scientist - Remote,Proven experience / Not specified years
35,Business Intelligence Analyst,Not specified

## Summary

This notebook cleaned and transformed the Saudi data jobs dataset to prepare it for further analysis.

Key observations:

- City values were standardized to improve consistency across locations.
- Experience levels and job titles were grouped into simplified categories for clearer analysis.
- A cleaned dataset was exported and prepared for visualization and Power BI development.

The cleaned dataset will be used in the following stages to analyze skills, tools, roles, and career readiness patterns.