In [1]:
import pandas as pd
from pathlib import Path

In [5]:
# File path
DATA_PATH = "saudi_data_jobs_dataset-2.csv"

# Read the raw dataset
df = pd.read_csv(DATA_PATH)

# Show first rows
df.head()

,job_id,job_title,company,city,role_type,experience_level,skills,tools,source,job_link,date_collected,notes
0,1,Data Analyst,ALESAYI HOLDING,Jeddah,Data Analyst,Entry level / 3 years,"customer data analysis, operational performanc...","Excel, PowerPoint, dashboards",LinkedIn,https://sa.linkedin.com/jobs/view/data-analyst...,2026-06-30,Customer experience data analyst role in autom...
1,2,Geological Data Scientist,Maaden Barrick Copper Company,Mahd Adh Dhahab,Data Scientist,Entry level / 2-5 years,"geological data management, data quality manag...","SQL, Python, Power BI, Tableau, relational dat...",LinkedIn,https://sa.linkedin.com/jobs/view/geological-d...,2026-06-30,Mining sector data science role. Focuses on ge...
2,3,Data Analyst,PrimeGate for Communications and IT,Riyadh,Data Analyst,Entry level,"data analysis, insights generation, dashboardi...","SQL, Power BI, Tableau, Looker, Excel, Python,...",LinkedIn,https://sa.linkedin.com/jobs/view/data-analyst...,2026-06-30,Entry-level data analyst role for Madinaty Sup...
3,4,Analyst Pricing Analytics and Insights,Schneider Electric,Saudi Arabia,Business / Pricing Analytics,Entry level,"pricing analytics, data analysis, data interpr...","data visualization, dashboards, charts, reports",LinkedIn,https://sa.linkedin.com/jobs/view/analyst-pric...,2026-06-30,Entry-level pricing analytics role. Focuses on...
4,5,Power BI Developer,Acuative Middle East,Jeddah,BI / Power BI Developer,Mid-level,"Power BI dashboard development, business intel...","Power BI Desktop, Power BI Service, DAX, Power...",LinkedIn,https://sa.linkedin.com/jobs/view/power-bi-dev...,2026-06-30,Mid-level Power BI Developer role in Jeddah. F...

In [6]:
# Check dataset shape
df.shape

(45, 12)

In [7]:
# Show column names
df.columns

Index(['job_id', 'job_title', 'company', 'city', 'role_type',
       'experience_level', 'skills', 'tools', 'source', 'job_link',
       'date_collected', 'notes'],
      dtype='object')

In [8]:
# General dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            45 non-null     int64
 1   job_title         45 non-null     object
 2   company           45 non-null     object
 3   city              45 non-null     object
 4   role_type         45 non-null     object
 5   experience_level  45 non-null     object
 6   skills            45 non-null     object
 7   tools             45 non-null     object
 8   source            45 non-null     object
 9   job_link          45 non-null     object
 10  date_collected    45 non-null     object
 11  notes             45 non-null     object
dtypes: int64(1), object(11)
memory usage: 4.3+ KB

In [9]:
# Check missing values
df.isnull().sum()

job_id              0
job_title           0
company             0
city                0
role_type           0
experience_level    0
skills              0
tools               0
source              0
job_link            0
date_collected      0
notes               0
dtype: int64

In [10]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [11]:
# Check duplicate job IDs
df["job_id"].duplicated().sum()

np.int64(0)

In [12]:
# Check duplicate job links
df["job_link"].duplicated().sum()

np.int64(0)

In [13]:
# Check city values
df["city"].value_counts()

city
Riyadh                         28
Jeddah                         10
Saudi Arabia                    5
Mahd Adh Dhahab                 1
King Abdullah Economic City     1
Name: count, dtype: int64

In [14]:
def clean_city(city):
    city = str(city).strip()

    if city in ["Riyadh", "الرياض"]:
        return "Riyadh"
    elif city in ["Jeddah", "جدة"]:
        return "Jeddah"
    elif city in ["Saudi Arabia", "السعودية"]:
        return "Not specified"
    elif city in ["King Abdullah Economic City"]:
        return "King Abdullah Economic City"
    elif city in ["Mahd Adh Dhahab"]:
        return "Mahd Adh Dhahab"
    else:
        return city

df["city_cleaned"] = df["city"].apply(clean_city)

df[["city", "city_cleaned"]].head(10)

              city     city_cleaned
0           Jeddah           Jeddah
1  Mahd Adh Dhahab  Mahd Adh Dhahab
2           Riyadh           Riyadh
3     Saudi Arabia    Not specified
4           Jeddah           Jeddah
5           Riyadh           Riyadh
6     Saudi Arabia    Not specified
7           Jeddah           Jeddah
8           Riyadh           Riyadh
9           Riyadh           Riyadh

In [15]:
# Check cleaned city values
df["city_cleaned"].value_counts()

city_cleaned
Riyadh                         28
Jeddah                         10
Not specified                   5
Mahd Adh Dhahab                 1
King Abdullah Economic City     1
Name: count, dtype: int64

In [16]:
# Check experience level values
df["experience_level"].value_counts()

experience_level
Entry level                                         3
Mid-level / 3+ years                                3
Entry level / 0-2 years                             2
Mid-level                                           2
Not specified                                       2
Proven experience / Not specified years             2
Internship / Co-op                                  2
Entry level / 2-5 years                             1
Entry level / 3 years                               1
Not applicable / 3+ years                           1
Associate / 3+ years                                1
Assistant level / 2+ years                          1
Entry level / 2 years                               1
Not applicable / 2+ years                           1
Mid-level / 2-4 years                               1
Entry level / 4-6 years                             1
Mid-level / 4+ years                                1
Entry level / Fresh graduate                        1
Associate                                           1
Assistant level / Analyst Program                   1
1+ years data analytics or automation experience    1
3-5+ years                                          1
0-3+ years                                          1
Basic proficiency / Qualification exam              1
1+ years professional experience                    1
4-10 years                                          1
Minimum 3 years                                     1
2+ years                                            1
Minimum 5 years                                     1
3-4 years                                           1
2-3 years                                           1
Minimum 4 years                                     1
Fresh graduate / Trainee                            1
Minimum 2 years                                     1
3-6 years                                           1
3-5 years                                           1
Name: count, dtype: int64

In [17]:
def categorize_experience(exp):
    exp = str(exp).lower().strip()

    if "internship" in exp or "co-op" in exp or "trainee" in exp:
        return "Internship"

    elif "fresh graduate" in exp:
        return "Entry Level"

    elif "entry" in exp:
        return "Entry Level"

    elif "0-2" in exp or "0 - 2" in exp:
        return "Entry Level"

    elif "1+" in exp or "2+" in exp or "2 years" in exp:
        return "Entry Level"

    elif "2-4" in exp or "2-5" in exp or "3+" in exp or "3-5" in exp or "3-6" in exp:
        return "Mid-Level"

    elif "4+" in exp or "4-6" in exp or "4-10" in exp or "minimum 4" in exp:
        return "Mid-Level"

    elif "minimum 5" in exp or "5 years" in exp or "senior" in exp:
        return "Senior"

    elif "associate" in exp or "assistant" in exp:
        return "Entry Level"

    elif "not specified" in exp or "not applicable" in exp or exp == "nan":
        return "Not Specified"

    else:
        return "Not Specified"

df["experience_category"] = df["experience_level"].apply(categorize_experience)

df[["experience_level", "experience_category"]].head(15)

                     experience_level experience_category
0               Entry level / 3 years         Entry Level
1             Entry level / 2-5 years         Entry Level
2                         Entry level         Entry Level
3                         Entry level         Entry Level
4                           Mid-level       Not Specified
5   Assistant level / Analyst Program         Entry Level
6             Entry level / 0-2 years         Entry Level
7          Assistant level / 2+ years         Entry Level
8                           Mid-level       Not Specified
9             Entry level / 0-2 years         Entry Level
10               Associate / 3+ years           Mid-Level
11          Not applicable / 3+ years           Mid-Level
12                 Internship / Co-op          Internship
13                          Associate         Entry Level
14                 Internship / Co-op          Internship

In [18]:
# Check experience category distribution
df["experience_category"].value_counts()

experience_category
Entry Level      18
Mid-Level        13
Not Specified    10
Internship        3
Senior            1
Name: count, dtype: int64

In [19]:
# Check role types
df["role_type"].value_counts()

role_type
Data Analyst                            4
Data Scientist                          4
Business Intelligence Analyst           3
Data Management / Governance            2
BI / Power BI Developer                 1
Business / Pricing Analytics            1
Fraud / Cybersecurity Analytics         1
Data / AI Analyst                       1
Digital Marketing Analytics             1
Product Analytics                       1
Market / Research Analytics             1
Performance / Operations Analytics      1
AI / Data-related Internship            1
Data Analyst / BI Analyst               1
Data Analyst / Performance Analytics    1
BI / Business Intelligence              1
Healthcare Analytics / AI               1
Aviation Safety Analytics               1
Research / Quantitative Analytics       1
IT / Data-related Internship            1
Business / Financial Analytics          1
Data Governance / Data Stewardship      1
Corporate Performance Analytics         1
AI / ML Engineering                     1
Data Science / AI Evaluation            1
Robotics Data Collection / AI Data      1
AI Data Annotation                      1
Operations / Inventory Analytics        1
Performance Analytics                   1
AI / ML Analytics                       1
Control and Reporting Analytics         1
Fraud Risk Analytics                    1
Medical Fraud Analytics                 1
AI / Data Trainee                       1
Commercial Performance Analytics        1
Data Quality Analyst                    1
Name: count, dtype: int64

In [20]:
def categorize_role(role):
    role = str(role).lower().strip()

    if "business intelligence" in role or "bi" in role or "power bi" in role:
        return "BI"

    elif "data scientist" in role or "data science" in role:
        return "Data Science"

    elif "ai" in role or "ml" in role or "machine learning" in role:
        return "AI"

    elif "data analyst" in role or "data analysis" in role:
        return "Data Analysis"

    elif "fraud" in role:
        return "Fraud Analytics"

    elif "governance" in role or "data management" in role or "data quality" in role or "stewardship" in role:
        return "Governance"

    elif "performance" in role or "operations" in role or "commercial" in role or "corporate performance" in role:
        return "Performance Analytics"

    elif "product" in role:
        return "Product Analytics"

    elif "marketing" in role:
        return "Marketing Analytics"

    elif "research" in role or "quantitative" in role or "market" in role:
        return "Research Analytics"

    elif "healthcare" in role or "medical" in role:
        return "Healthcare Analytics"

    elif "pricing" in role or "financial" in role or "control and reporting" in role:
        return "Business / Financial Analytics"

    elif "internship" in role or "trainee" in role or "co-op" in role:
        return "Internship / Training"

    else:
        return "Other"

df["role_category"] = df["role_type"].apply(categorize_role)

df[["role_type", "role_category"]].head(20)

                               role_type                   role_category
0                           Data Analyst                   Data Analysis
1                         Data Scientist                    Data Science
2                           Data Analyst                   Data Analysis
3           Business / Pricing Analytics  Business / Financial Analytics
4                BI / Power BI Developer                              BI
5                      Data / AI Analyst                              AI
6                         Data Scientist                    Data Science
7     Performance / Operations Analytics           Performance Analytics
8        Fraud / Cybersecurity Analytics                 Fraud Analytics
9            Digital Marketing Analytics             Marketing Analytics
10                     Product Analytics               Product Analytics
11           Market / Research Analytics              Research Analytics
12          IT / Data-related Internship           Internship / Training
13          Data Management / Governance                      Governance
14          AI / Data-related Internship                              AI
15             Data Analyst / BI Analyst                              BI
16  Data Analyst / Performance Analytics                   Data Analysis
17            BI / Business Intelligence                              BI
18             Healthcare Analytics / AI                              AI
19             Aviation Safety Analytics                           Other

In [21]:
# Check role category distribution
df["role_category"].value_counts()

role_category
AI                                8
BI                                6
Data Analysis                     5
Data Science                      5
Performance Analytics             5
Governance                        4
Business / Financial Analytics    3
Fraud Analytics                   3
Research Analytics                2
Product Analytics                 1
Marketing Analytics               1
Internship / Training             1
Other                             1
Name: count, dtype: int64

In [22]:
# Preview important columns after cleaning
df[[
    "job_id",
    "job_title",
    "company",
    "city",
    "city_cleaned",
    "experience_level",
    "experience_category",
    "role_type",
    "role_category"
]].head(20)

,job_id,job_title,company,city,city_cleaned,experience_level,experience_category,role_type,role_category
0,1,Data Analyst,ALESAYI HOLDING,Jeddah,Jeddah,Entry level / 3 years,Entry Level,Data Analyst,Data Analysis
1,2,Geological Data Scientist,Maaden Barrick Copper Company,Mahd Adh Dhahab,Mahd Adh Dhahab,Entry level / 2-5 years,Entry Level,Data Scientist,Data Science
2,3,Data Analyst,PrimeGate for Communications and IT,Riyadh,Riyadh,Entry level,Entry Level,Data Analyst,Data Analysis
3,4,Analyst Pricing Analytics and Insights,Schneider Electric,Saudi Arabia,Not specified,Entry level,Entry Level,Business / Pricing Analytics,Business / Financial Analytics
4,5,Power BI Developer,Acuative Middle East,Jeddah,Jeddah,Mid-level,Not Specified,BI / Power BI Developer,BI
5,6,2026 KSA Analyst Program - Data and AI Analyst,Infinite PL,Riyadh,Riyadh,Assistant level / Analyst Program,Entry Level,Data / AI Analyst,AI
6,7,Data Scientist I,MOZN,Saudi Arabia,Not specified,Entry level / 0-2 years,Entry Level,Data Scientist,Data Science
7,8,Specialist Operations Performance,DP World,Jeddah,Jeddah,Assistant level / 2+ years,Entry Level,Performance / Operations Analytics,Performance Analytics
8,9,Data Analyst Fraud Protection,Group-IB,Riyadh,Riyadh,Mid-level,Not Specified,Fraud / Cybersecurity Analytics,Fraud Analytics
9,10,Junior Digital Marketing Analyst,Aqar,Riyadh,Riyadh,Entry level / 0-2 years,Entry Level,Digital Marketing Analytics,Marketing Analytics
10,11,Product Analyst,Gathern.co,Riyadh,Riyadh,Associate / 3+ years,Mid-Level,Product Analytics,Product Analytics
11,12,Analyst Data Center Services and Infrastructur...,S&P Global,Riyadh,Riyadh,Not applicable / 3+ years,Mid-Level,Market / Research Analytics,Research Analytics
12,13,Elm Co-op Training Program August 2026 Intake ...,Elm,Riyadh,Riyadh,Internship / Co-op,Internship,IT / Data-related Internship,Internship / Training
13,14,Data Management Specialist,Muller's Solutions,Saudi Arabia,Not specified,Associate,Entry Level,Data Management / Governance,Governance
14,15,Technical Co-op - Artificial Intelligence,HUMAIN,Riyadh,Riyadh,Internship / Co-op,Internship,AI / Data-related Internship,AI
15,16,MI and Data Analysis Analyst,FNRCO,Riyadh,Riyadh,Entry level / 2 years,Entry Level,Data Analyst / BI Analyst,BI
16,17,Data Analyst - KPIs and Report,AtkinsRéalis,Riyadh,Riyadh,Mid-level / 3+ years,Mid-Level,Data Analyst / Performance Analytics,Data Analysis
17,18,Business Intelligence Developer,Saudi Air Navigation Services,Saudi Arabia,Not specified,Entry level,Entry Level,BI / Business Intelligence,BI
18,19,Capabilities and Insights Analytics Analyst - ...,McKinsey and Company,Riyadh,Riyadh,Mid-level / 3+ years,Mid-Level,Healthcare Analytics / AI,AI
19,20,Flight Data Analysis Officer,Riyadh Air,Riyadh,Riyadh,Mid-level / 3+ years,Mid-Level,Aviation Safety Analytics,Other

In [23]:
# Check final shape after cleaning
df.shape

(45, 15)

In [24]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate job IDs:", df["job_id"].duplicated().sum())
print("Duplicate job links:", df["job_link"].duplicated().sum())

Duplicate rows: 0
Duplicate job IDs: 0
Duplicate job links: 0

In [25]:
# Check missing values after cleaning
df.isnull().sum()

job_id                 0
job_title              0
company                0
city                   0
role_type              0
experience_level       0
skills                 0
tools                  0
source                 0
job_link               0
date_collected         0
notes                  0
city_cleaned           0
experience_category    0
role_category          0
dtype: int64

In [26]:
print("Final dataset summary")
print("----------------------")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate job IDs:", df["job_id"].duplicated().sum())
print("Duplicate job links:", df["job_link"].duplicated().sum())

print("\nCity distribution:")
print(df["city_cleaned"].value_counts())

print("\nExperience category distribution:")
print(df["experience_category"].value_counts())

print("\nRole category distribution:")
print(df["role_category"].value_counts())

Final dataset summary
----------------------
Rows: 45
Columns: 15
Duplicate rows: 0
Duplicate job IDs: 0
Duplicate job links: 0

City distribution:
city_cleaned
Riyadh                         28
Jeddah                         10
Not specified                   5
Mahd Adh Dhahab                 1
King Abdullah Economic City     1
Name: count, dtype: int64

Experience category distribution:
experience_category
Entry Level      18
Mid-Level        13
Not Specified    10
Internship        3
Senior            1
Name: count, dtype: int64

Role category distribution:
role_category
AI                                8
BI                                6
Data Analysis                     5
Data Science                      5
Performance Analytics             5
Governance                        4
Business / Financial Analytics    3
Fraud Analytics                   3
Research Analytics                2
Product Analytics                 1
Marketing Analytics               1
Internship / Training             1
Other                             1
Name: count, dtype: int64

In [27]:
# Save cleaned dataset
OUTPUT_PATH = "saudi_data_jobs_cleaned.csv"

df.to_csv(OUTPUT_PATH, index=False)

print("Cleaned dataset saved as:", OUTPUT_PATH)

Cleaned dataset saved as: saudi_data_jobs_cleaned.csv

In [28]:
from google.colab import files

files.download("saudi_data_jobs_cleaned.csv")

## Day 17 Cleaning Summary

In this notebook, I cleaned the expanded Saudi data jobs dataset after increasing it to 45 job postings.

The cleaning process included:
- Checking dataset shape and columns
- Checking missing values
- Checking duplicate rows
- Checking duplicate job IDs
- Checking duplicate job links
- Creating `city_cleaned`
- Creating `experience_category`
- Creating `role_category`
- Saving the updated cleaned dataset as `saudi_data_jobs_cleaned.csv`

Main output:
- The cleaned dataset now contains 45 job postings.
- The dataset includes 15 columns after adding the three analysis-ready columns.
- The cleaned dataset is ready for updated analysis and visualization.